oshiro_navi/event_info_management/urls.py
from django.urls import path

from .views import *

app_name = 'event_info_management'

urlpatterns = [
    path('admin/list/', AdminEventInfoListView.as_view(), name='admin_event_info_list'),
    path('admin/register/',AdminEventInfoRegisterView.as_view(), name='admin_event_info_register'),
    path('admin/register_success/',AdminEventInfoRegisterSuccessView.as_view(), name='admin_event_info_register_success'),
    path('admin/update/<int:pk>/', AdminEventInfoUpdateView.as_view(), name='admin_event_info_update'),
    path('admin/update_success/',AdminEventInfoUpdateSuccessView.as_view(), name='admin_event_info_update_success'),
    path('admin/delete/<int:pk>/', AdminEventInfoDeleteView.as_view(), name='admin_event_info_delete'),
    path('admin/delete_success/',AdminEventInfoDeleteSuccessView.as_view(), name='admin_event_info_delete_success'),
    path('Admin/detail/<int:pk>/',AdminEventInfoDetailView.as_view(), name='admin_event_info_detail'),

    path('operator/list/', OperatorEventInfoListView.as_view(), name='operator_event_info_list'),
    path('operator/register/',OperatorEventInfoRegisterView.as_view(), name='operator_event_info_register'),
    path('operator/register_success/',OperatorEventInfoRegisterSuccessView.as_view(), name='operator_event_info_register_success'),
    path('operator/update/<int:pk>/',OperatorEventInfoUpdateView.as_view(), name='operator_event_info_update'),
    path('operator/update_success/',OperatorEventInfoUpdateSuccessView.as_view(), name='operator_event_info_update_success'),
    path('operator/delete/<int:pk>/',OperatorEventInfoDeleteView.as_view(), name='operator_event_info_delete'),
    path('operator/delete_success/',OperatorEventInfoDeleteSuccessView.as_view(), name='operator_event_info_delete_success'),
    path('operator/detail/<int:pk>/',OperatorEventInfoDetailView.as_view(), name='operator_event_info_detail'),
]

oshiro_navi/operator_accounts/urls.py
from django.urls import path

from .views import *

app_name = "operator_accounts"

urlpatterns = [
    path('',OperatorLoginView.as_view(), name='operator_login'),
    path('logout/',OperatorLogoutView.as_view(), name='operator_logout'),
    path('top/', OperatorTopView.as_view(), name='top'),
    path('top/list/', AdminAccountListView.as_view(), name='account_list'),
    path('top/list/create/',AdminAccountCreateView.as_view(), name='account_create'),
    path('top/list/create/success/',AdminAccountCreateSuccessView.as_view(), name='account_create_success'),
    path('top/list/delete/<int:pk>/', AdminAccountDeleteView.as_view(), name='account_delete'),
    path('top/list/delete/success/', AdminAccountDeleteSuccessView.as_view(), name='account_delete_success'),

]

oshiro_navi/operator_oshiro_info/urls.py
from django.urls import path

from .views import *

app_name = "operator_oshiro_info"

urlpatterns = [
    path('list/',OshiroInfoListView.as_view(), name='list'),
    path('register/',OshiroInfoRegisterView.as_view(), name='register'),
    path('register_success/',OshiroInfoRegisterSuccessView.as_view(), name='register_success'),
    path('update/',OshiroInfoUpdateView.as_view(), name='update'),
    path('update_success/',OshiroInfoUpdateSuccessView.as_view(), name='update_success'),





]

oshiro_navi/oshiro_navi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin_site/', admin.site.urls),

    # --- 運営アカウント機能 ---
    path('operator/', include('operator_accounts.urls')),

    # # --- お城情報管理 ---
    path('operator/oshiro/', include('operator_oshiro_info.urls')),

    # --- 管理者アカウント機能 ---
    path('admin/', include('admin_accounts.urls')),

    # --- 管理者周辺MAP機能 ---
    path('admin/area_map/', include('admin_area_map.urls')),

    # # --- 管理者音声ガイド機能 ---
    path('admin/audio_guide/', include('admin_audio_guide.urls')),

    # --- 管理者お城スタンプ機能 ---
    path("admin_oshiro_stamp/", include("admin_oshiro_stamp.urls")),

    # # --- 管理者モデルコース機能 ---
    path('admin/model_course/', include('admin_model_course.urls')),

    # # --- 管理者基本情報機能 ---
    path('admin/basic_info/', include('admin_basic_info.urls')),

    # # --- 利用者アカウント機能 ---
    path('user/', include('user_accounts.urls')),

    # # --- 利用者音声ガイド機能 ---
    path('user/audio_guide/', include('user_audio_guide.urls')),

    # # --- 利用者モデルコース機能 ---
    path('user_model_course/', include('user_model_course.urls')),

    # # --- 利用者イベント機能 ---
    path('user_event_info/', include('user_event_info.urls')),

    # # --- 利用者お城リスト機能 ---
    path('usermy_list/', include('user_my_list.urls')),
    
    # # --- 利用者マイページ機能 ---
    path('usermy_page/', include('user_my_page.urls')),

    # # --- イベント情報機能 ---
    path('event_management/', include('event_info_management.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oshiro_navi/operator_accounts/models.py
import math
from django.db import models
from django.conf import settings 

class Operator(models.Model):
    account = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="operator_profile",
        help_text="運営としてのアカウント"
    )

    class Meta:
        db_table = "operator"
        verbose_name = "運営"
        verbose_name_plural = "運営"

    def __str__(self):
        return f"Operator({self.account.username})"
    
    @staticmethod
    def calculate_distance(lat1, lon1, lat2, lon2):
        """
        2点の緯度経度から距離（メートル）を計算する（ハバーシン公式）
        """
        R = 6371000  # 地球の半径（メートル）
        phi1 = math.radians(lat1)
        phi2 = math.radians(lat2)
        delta_phi = math.radians(lat2 - lat1)
        delta_lambda = math.radians(lon2 - lon1)

        # ここから下の計算も関数の中にインデントする必要があります
        a = math.sin(delta_phi / 2)**2 + \
            math.cos(phi1) * math.cos(phi2) * \
            math.sin(delta_lambda / 2)**2
        c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))

        return R * c  # 距離（m）を返す

oshiro_navi/operator_accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from admin_accounts.models import Admin
from operator_oshiro_info.models import OshiroInfo

User = get_user_model()

class AdminUserCreateForm(forms.ModelForm):
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput)

    managed_castles = forms.Field(
        label="担当するお城（最大5つ）",
        required=False,
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password','account_name']

    def clean_managed_castles(self):
        #送信されたデータが入っています
        castle_ids = self.data.getlist('managed_castles')
        
        # 数字（ID）だけを取り出し、実際にお城がDBに存在するか確認する
        valid_castles = []
        # 重複を避けるために set を使って ID を管理
        seen_ids = set()

        for cid in castle_ids:
            if cid and cid.isdigit() and cid not in seen_ids:
                try:
                    oshiro = OshiroInfo.objects.get(id=cid)
                    valid_castles.append(oshiro)
                    seen_ids.add(cid)
                except OshiroInfo.DoesNotExist:
                    continue # 存在しないIDは無視
        
        # 最大数チェック
        if len(valid_castles) > 5:
            raise forms.ValidationError("管理できるお城は最大5つまでです。")

        # お城のインスタンスのリストを返す
        return valid_castles

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        user.is_staff = True 
        
        if commit:
            user.save()
            admin_profile = Admin.objects.create(account=user)

            # clean_managed_castles が返したリストを取得
            selected_castles = self.cleaned_data.get('managed_castles', [])

            # スロットに割り当て
            if len(selected_castles) >= 1: admin_profile.oshiro_management1 = selected_castles[0]
            if len(selected_castles) >= 2: admin_profile.oshiro_management2 = selected_castles[1]
            if len(selected_castles) >= 3: admin_profile.oshiro_management3 = selected_castles[2]
            if len(selected_castles) >= 4: admin_profile.oshiro_management4 = selected_castles[3]
            if len(selected_castles) >= 5: admin_profile.oshiro_management5 = selected_castles[4]
            
            admin_profile.save()
        return user

oshiro_navi/operator_accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DeleteView,ListView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from operator_oshiro_info.models import OshiroInfo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.db.models import Q
from .forms import AdminUserCreateForm
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.views import View
from operator_accounts.models import Operator
from django.contrib.auth import authenticate, login
from django.urls import reverse

# Create your views here.
User = get_user_model()

class OperatorTopView(LoginRequiredMixin,TemplateView):
    template_name = "operator_top.html"
    login_url = reverse_lazy("operator_accounts:operator_login")  
    redirect_field_name = "next"

class AdminAccountListView(ListView):
    model = User # get_user_model()したもの
    template_name = 'admin_account_list.html'
    context_object_name = 'account_list'

    def get_queryset(self):
        queryset = super().get_queryset().select_related(
            'admin_profile',
            'admin_profile__oshiro_management1',
            'admin_profile__oshiro_management2',
            'admin_profile__oshiro_management3',
            'admin_profile__oshiro_management4',
            'admin_profile__oshiro_management5',
        ).filter(is_staff=True, admin_profile__isnull=False)

        # 
        q_word = self.request.GET.get('search')
        if q_word:
            queryset = queryset.filter(
                Q(username__icontains=q_word) | 
                Q(email__icontains=q_word)
            )
        
        return queryset

class AdminAccountCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = AdminUserCreateForm
    template_name = "admin_account_create.html"
    success_url = reverse_lazy('operator_accounts:account_create_success') 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # HTMLで「castle_list」という名前でお城の全データを使えるようにする
        context['castle_list'] = OshiroInfo.objects.all()
        return context

    def test_func(self):
        # 運営（スーパーユーザー）のみ実行可能
        return self.request.user.is_superuser

class AdminAccountCreateSuccessView(TemplateView):
    template_name = "admin_account_create_success.html"

class AdminAccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy('operator_accounts:account_delete_success')

    template_name = 'admin_account_list.html' 

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

class AdminAccountDeleteSuccessView(TemplateView):
    template_name = "admin_account_delete_success.html"

# ログイン画面
class OperatorLoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            # すでにログインしている場合、Operatorならトップへ、そうでなければログアウトさせる等の処理
            return redirect('operator_accounts:top')
        return render(request, 'operator_login.html')

    def post(self, request):
        admin_id = request.POST.get('id')
        admin_pass = request.POST.get('pass')

        # 1. まずはユーザーを認証（IDとパスワードの照合）
        user = authenticate(request, username=admin_id, password=admin_pass)

        if user is not None:
            # 2. 【重要】そのユーザーが「運営アカウント(Operator)」かチェック
            is_operator = Operator.objects.filter(account=user).exists()
            
            if is_operator:
                # 運営アカウントであればログイン成功
                login(request, user)
                return redirect('operator_accounts:top')
            else:
                # ユーザーは存在するが、運営アカウントではない（管理者や一般ユーザー）場合
                context = {
                    'error': 'このアカウントは運営用ではありません。',
                    'prev_id': admin_id,
                }
                return render(request, 'operator_login.html', context)
        else:
            # 3. 認証失敗（IDまたはパスワード間違い）
            context = {
                'error': 'IDまたはパスワードが正しくありません。',
                'prev_id': admin_id,
            }
            return render(request, 'operator_login.html', context)
        

# ログアウト画面
class OperatorLogoutView(LogoutView):
    template_name = "operator_logout.html"

oshiro_navi/operator_accounts/templates/admin_account_create.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}管理者アカウント登録{% endblock %}
{% block content %}


<div class="content-container">
    <h1>管理者アカウント登録</h1>
    <hr style="width:80%; margin-bottom: 10px; margin-top: 10px;"> 
    <p style="color:red;">＊がついている項目は必須です</p>
    <form method="POST"  class="form-container">
        {% csrf_token %}
        {% if form.errors %}
        <div style="background: #ffdada; padding: 10px; border: 1px solid red; margin-bottom: 20px;">
            <p>エラーが発生しています：</p>
            <ul>
            {% for field, errors in form.errors.items %}
                <li>{{ field }}: {{ errors|striptags }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% if form.managed_castles.errors %}
        <div class="alert alert-danger" style="color: red; border: 1px solid red; padding: 10px; margin-bottom: 10px;">
            {{ form.managed_castles.errors }}
        </div>
        {% endif %}
        <table class="basic-info-table" border="1" cellpadding="8" cellspacing="0" style="margin-bottom: 10px;">
            <!-- アカウント名 -->
            <tr>
                <th>アカウント名<p class="required-point">＊</p></th>
                <td>
                <input type="account_name" name="account_name" placeholder="アカウント名" required>
                </td>
            </tr>

            <!-- ID -->
            <tr>
                <th>ID<p class="required-point">＊</p></th>
                <td>
                <input type="text" name="username" placeholder="ID(6文字以内)" required>
                </td>
            </tr>

            <!-- Pass -->
            <tr>
                <th>Pass <p class="required-point">＊</p></th>
                <td>
                <input type="password" name="password" placeholder="Pass" required>
                </td>
            </tr>

            <!-- Email -->
            <tr>
                <th>Email <p class="required-point">＊</p></th>
                <td>
                <input type="email" name="email" placeholder="Email" required>
                </td>
            </tr>

            <!-- 担当お城の選択（最大5つ） -->
            <tr>
                <th> 担当お城の選択<br>（最大5つ）<p class="required-point">＊</p></th>
                <td>
                    {% for i in "12345" %}
                    <div class="my-custom-wrapper">
                        <label>担当お城 {{ forloop.counter }}</label>
                        <select name="managed_castles" class="form-control">
                            <option value="none">お城を選択しない</option>
                            {% for oshiro in castle_list %}
                                <option value="{{ oshiro.id }}">
                                    {{ oshiro.oshiro_name }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    {% endfor %}
                </td>
            </tr>
        </table>
        <input class="btn btn-register" type="submit" value="登録" />
        <a href="{% url 'operator_accounts:account_list' %}" class="btn btn-cancel">
                戻る
            </a>
    </form>
</div>
{% endblock %}

oshiro_navi/operator_accounts/templates/admin_account_create_success.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}管理者アカウントの作成完了{% endblock %}
{% block content %}
<div class="content-container">
    <h1 class="page-title">管理者アカウントの作成完了</h1>
    <hr style="width:80%; margin-bottom: 10px; margin-top: 10px;"> 
    管理者アカウントの作成が完了しました。
    <a href="{% url 'operator_accounts:account_list' %}" class="btn btn-cancel">
        管理者アカウント一覧へ戻る
    </a>
</div>
{% endblock %}

oshiro_navi/operator_accounts/templates/admin_account_delete.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}管理者アカウント削除{% endblock %}
{% block content %}
<div class="content-container">
    <h1>管理者アカウント削除</h1>
    <p>本当にこの管理者アカウントを削除してもよろしいですか？</p>

    <form action="{% url 'operator_accounts:account_delete_success' %}" method="GET" class="form-container">
        {% csrf_token %}
        <input class="btn btn-delete" type="submit" value="削除" />
        <a href="{% url 'operator_accounts:account_list' %}" class="btn btn-cancel">
            キャンセル
        </a>
    </form>
</div>
{% endblock %}

oshiro_navi/operator_accounts/templates/admin_account_delete_success.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}管理者アカウントの削除完了{% endblock %}
{% block content %}
<div class="content-container">
    <h1 class="page-title">管理者アカウントの削除新完了</h1>
    <hr style="width:80%; margin-bottom: 10px; margin-top: 10px;"> 
    管理者アカウントの削除が完了しました。
    <a href="{% url 'operator_accounts:account_list' %}" class="btn btn-cancel">
        管理者アカウント一覧へ戻る
    </a>
</div>
{% endblock %}

oshiro_navi/operator_accounts/templates/admin_account_list.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}管理者アカウント一覧{% endblock %}

{% block content %}
<div class="content-container">
    <div class="profile-info">
        <h1>管理者アカウント一覧</h1>
    </div>
    <hr style="width:80%; margin-bottom: 10px; margin-top: 10px;">

    <div class="top-bar">
        <form method="get" action="">
        <input type="text" name="search" value="{{ request.GET.search }}" placeholder="名前やメールで検索" style="width: 300px; padding: 5px; margin-right: 10px;">
        <button type="submit" class="btn btn-search">検索</button>
        <a href="{% url 'operator_accounts:account_create' %}" class="btn btn-register" style="margin-left: 10px;"">＋新規管理者アカウント作成</a>
    </form>
    </div>

    <section class="table-area">
        <div class="admin-account-list">
            <table class="admin-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>アカウント名</th>
                        <th>メールアドレス</th>
                        <th>担当お城</th>
                        <th>最終ログイン</th>
                        <th class="txt-center">操作</th>
                    </tr>
                </thead>

                <tbody>
                    {% for account in object_list %}
                    <tr>
                        <td>{{ account.username }}</td>
                        <td>{{ account.account_name }}</td>
                        <td>{{ account.email }}</td>
                        
                        
                        <td>
                            {% with admin=account.admin_profile %}
                                {% if admin %}
                                    {% if admin.oshiro_management1 %}{{ admin.oshiro_management1.oshiro_name }}<br>{% endif %}
                                    {% if admin.oshiro_management2 %}{{ admin.oshiro_management2.oshiro_name }}<br>{% endif %}
                                    {% if admin.oshiro_management3 %}{{ admin.oshiro_management3.oshiro_name }}<br>{% endif %}
                                    {% if admin.oshiro_management4 %}{{ admin.oshiro_management4.oshiro_name }}<br>{% endif %}
                                    {% if admin.oshiro_management5 %}{{ admin.oshiro_management5.oshiro_name }}<br>{% endif %}
                                    
                                    {% if not admin.oshiro_management1 %}
                                        <span style="color: #ccc;">未設定</span>
                                    {% endif %}
                                {% else %}
                                    <span style="color: #ccc;">担当無し</span>
                                {% endif %}
                            {% endwith %}
                        </td>

                        <td>{{ account.last_login|date:"Y-m-d H:i" }}</td>
                        <td class="txt-center">
                            <a href="{% url 'operator_accounts:account_delete' account.pk %}" 
                                class="btn btn-delete" 
                                onclick="return confirm('本当にこのアカウント（{{ account.username }}）を削除してもよろしいですか？');">
                                削除
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="7" class="txt-center">データが見つかりませんでした。</td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
        </div>
    </section>
</div>
{% endblock %}

oshiro_navi/operator_accounts/templates/operator_login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログイン画面</title>
    <link rel="stylesheet" href="{% static 'css/admin_op_base.css' %}">
</head>

<body> 
<div class="login_container">
    <h1>運営アカウントに<br>ログインしてください</h1>

    {% if error %}
        <p style="color: red; text-align: center;">{{ error }}</p>
    {% endif %}

    <form class="login_form" action="{% url 'operator_accounts:operator_login' %}" method="POST">
        {% csrf_token %}
        
        <span class="login-span">
            <label for="id" class="label">ID</label>
            <input type="text" name="id" id="id" value="{{ prev_id|default:'' }}" required/>
        </span>
        
        <span class="login-span">
            <label for="pass" class="label">Pass</label>
            <input type="password" name="pass" id="pass" required/>
        </span>
        <input class="btn btn-register" type="submit" value="Login" />
    </form>
</div>

</body>
</html>

oshiro_navi/operator_accounts/templates/operator_logout.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログアウト画面</title>
    <link rel="stylesheet" href="{% static 'css/admin_op_base.css' %}">



</head>

<body> 
    <div class="logout_container">
        <h1 class="page-title">ログアウトしました。</h1>
        <a href="{% url 'operator_accounts:operator_login' %}" class="btn btn-cancel">ログイン画面へ戻る</a>
    </div> 
</body>
</html>

oshiro_navi/operator_accounts/templates/operator_top.html
{% extends "operator_base.html" %}
{% load static %}
{% block title %}運営TOP{% endblock %}
{% block content %}
    <body>
    <!-- メイン -->
    <div class="content">
        <h1>運営 TOP</h1>

        <div class="menu-grid">
            <div class="menu-card" onclick="location.href='{% url 'operator_oshiro_info:list' %}'">
                <i class="material-symbols-outlined">edit_document</i> お城情報機能
            </div>
            <div class="menu-card" onclick="location.href='{% url 'event_info_management:operator_event_info_list' %}'">
                <i class="material-symbols-outlined">calendar_month</i> イベント情報機能
            </div>
            <div class="menu-card" onclick="location.href='{% url 'operator_accounts:account_list' %}'">
                <i class="material-symbols-outlined">manage_accounts</i> アカウント機能
            </div>
            <div class="logout menu-card" onclick="location.href='{% url 'operator_accounts:operator_logout' %}'">
                <i class="material-symbols-outlined">logout</i> ログアウト
            </div>
        </div>
    </div>

    </body>
{% endblock %}