oshiro_navi/admin_accounts/urls.py
from django.urls import path

from .views import *

app_name = "admin_accounts"

urlpatterns = [
    path('login/', AdminLoginView.as_view(), name='login'),
    path('logout/', AdminLogoutView.as_view(), name='logout'),
    path('top/', AdminTopView.as_view(), name='top'),

]

oshiro_navi/oshiro_navi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('admin_site/', admin.site.urls),

    # --- 運営アカウント機能 ---
    path('operator/', include('operator_accounts.urls')),

    # # --- お城情報管理 ---
    path('operator/oshiro/', include('operator_oshiro_info.urls')),

    # --- 管理者アカウント機能 ---
    path('admin/', include('admin_accounts.urls')),

    # --- 管理者周辺MAP機能 ---
    path('admin/area_map/', include('admin_area_map.urls')),

    # # --- 管理者音声ガイド機能 ---
    path('admin/audio_guide/', include('admin_audio_guide.urls')),

    # --- 管理者お城スタンプ機能 ---
    path("admin_oshiro_stamp/", include("admin_oshiro_stamp.urls")),

    # # --- 管理者モデルコース機能 ---
    path('admin/model_course/', include('admin_model_course.urls')),

    # # --- 管理者基本情報機能 ---
    path('admin/basic_info/', include('admin_basic_info.urls')),

    # # --- 利用者アカウント機能 ---
    path('user/', include('user_accounts.urls')),

    # # --- 利用者音声ガイド機能 ---
    path('user/audio_guide/', include('user_audio_guide.urls')),

    # # --- 利用者モデルコース機能 ---
    path('user_model_course/', include('user_model_course.urls')),

    # # --- 利用者イベント機能 ---
    path('user_event_info/', include('user_event_info.urls')),

    # # --- 利用者お城リスト機能 ---
    path('usermy_list/', include('user_my_list.urls')),
    
    # # --- 利用者マイページ機能 ---
    path('usermy_page/', include('user_my_page.urls')),

    # # --- イベント情報機能 ---
    path('event_management/', include('event_info_management.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oshiro_navi/user_accounts/urls.py
from django.urls import path

from .views import *

app_name = "user_accounts"

urlpatterns = [

    # ユーザーTop画面
    path('top/', UserTopView.as_view(), name='top'),

    # ログアウト画面
    path('logout/', UserlogoutView.as_view(), name='logout'),
    path('logout_check/', UserlogoutCheckView.as_view(), name='logout_check'),

    # サインアップ・ログイン画面
    path('account/', UserAccountView.as_view(), name='account'),
    
]

oshiro_navi/user_my_list/urls.py
from django.urls import path
from .views import *

app_name = "usermy_list"

urlpatterns = [ 
    path('oshirolist/', OshirolistView.as_view(), name='oshirolist'),
    path('oshiro_info/<int:pk>/', OshiroInfoView.as_view(), name='oshiroinfo'),
    path('oshiro_basic_info/<int:pk>/', OshiroBasicInfoView.as_view(), name='oshirobasicinfo'),
    path('review/<int:pk>/', OshiroReviewView.as_view(), name='oshiroreview'),
    path('oshiroaftersearch/', OshiroAfterSearchView.as_view(), name='aftersearch'),
    path('oshiromap/<int:pk>/', OshiroMapView.as_view(), name='oshiromap'),
    path('review/delete/<int:pk>/', delete_review, name='delete_review'),
]

oshiro_navi/user_my_page/urls.py
from django.urls import path
from . import views  # viewsをモジュールとしてインポートする方法に統一するのが安全です

app_name = "usermy_page"

urlpatterns = [
    path('mypage/', views.MyPageTopView.as_view(), name='mypage'),
    path('mylistregistar/', views.MyListRegistarView.as_view(), name='mylistregistar'), 
    path('mylistdeletecheck/<int:pk>/', views.MyListDeleteCheckView.as_view(), name='mylistdeletecheck'),
    path('profileupdate/', views.ProfileCompleteView.as_view(), name='profileupdate'),
    path('profile/', views.ProfileEditView.as_view(), name='profile'),
    path('mylistdelete/', views.MyListDeleteView.as_view(), name='mylistdelete'),
    path('userprofile/<int:user_id>/', views.UserProfileView.as_view(), name='otherprofile'),
    path('get_stamp/', views.GetStampView.as_view(), name='get_stamp'),
    path('oshirostampregistar/', views.OshiroStampBookView.as_view(), name='oshirostampregistar'),
]

oshiro_navi/oshiro_navi/templates/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}管理者画面{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/admin_op_base.css' %}">
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
</head>

<body>
<!-- サイドバークラス -->
<div class="sidebar">
    <ul class="nav">
        <li>
            <a href="{% url 'admin_accounts:top' %}">
                <i class="material-symbols-outlined">home</i>
                <span class="link_name">管理者TOP画面</span>
            </a>
            <span class="tooltip">管理者TOP画面</span>
        </li>
        <li>
            <a href="{% url 'admin_basic_info:basic_info_list' %}">
                <i class="material-symbols-outlined">edit_document</i>
                <span class="link_name">基本情報機能</span>
            </a>
            <span class="tooltip">基本情報機能</span>
        </li>

        <li>
            <a href= "{% url 'admin_area_map:area_map' %}">
                <i class="material-symbols-outlined">map_pin_review</i>
                <span class="link_name">周辺MAP機能</span>
            </a>
            <span class="tooltip">周辺MAP機能</span>
        </li>

        <li>
            <a href="{% url 'event_info_management:admin_event_info_list' %}">
                <i class="material-symbols-outlined">calendar_month</i>
                <span class="link_name">イベント情報機能</span>
            </a>
            <span class="tooltip">イベント情報機能</span>
        </li>

        <li>
            <a href= "{% url 'admin_audio_guide:audio_guide' %}">
                <i class="material-symbols-outlined">record_voice_over</i>
                <span class="link_name">音声ガイド機能</span>
            </a>
            <span class="tooltip">音声ガイド機能</span>
        </li>

        <li>
            <a href="{% url 'admin_oshiro_stamp:oshiro_stamp_list' %}">
                <i class="material-symbols-outlined">approval</i>
                <span class="link_name">お城スタンプ機能</span>
            </a>
            <span class="tooltip">お城スタンプ機能</span>
        </li>

        <li>
            <a href="{% url 'admin_model_course:model_couse_search' %}">
                <i class="material-symbols-outlined">alt_route</i> 
                <span class="link_name">モデルコース機能</span>
            </a>
            <span class="tooltip">モデルコース機能</span>
        </li>
        <li>
            <a href="{% url 'admin_audio_guide:qr_generetor' %}">
                <i class="material-symbols-outlined">qr_code_2_add</i>
                <span class="link_name">QRコード生成</span>
            </a>
            <span class="tooltip">QRコード生成</span>
        </li>
        <li>
            <a href="{% url 'admin_accounts:logout' %}" class="logout">
                <i class="material-symbols-outlined">logout</i>
                <span class="link_name">ログアウト</span>
            </a>
            <span class="tooltip">ログアウト</span>
        </li>
    </ul>
</div>
<!-- ▲ サイドバー（共通） ▲ -->


<!-- ▼ ページごとの中身を入れる部分 ▼ -->
<div class="home_content" id="no name">
    {% block content %}
    {% endblock %}
</div>
<!-- ▲ ページごとの中身 ▲ -->


</body>
</html>

oshiro_navi/oshiro_navi/templates/operator_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}運営画面{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/admin_op_base.css' %}">
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
</head>

<body>

<!-- ▼ サイドバー（共通） ▼ -->
<div class="sidebar">
    <ul class="nav">
        <li>
            <a href="{% url 'operator_accounts:top' %}">
                <i class="material-symbols-outlined">home</i>
                <span class="link_name">運営TOP画面</span>
            </a>
            <span class="tooltip">運営TOP画面</span>
        </li>

        <li>
            <a href="{% url 'operator_oshiro_info:list' %}">
                <i class="material-symbols-outlined">edit_document</i>
                <span class="link_name">お城情報機能</span>
            </a>
            <span class="tooltip">お城情報機能</span>
        </li>

        <li>
            <a href="{% url 'event_info_management:operator_event_info_list' %}">
                <i class="material-symbols-outlined">calendar_month</i>
                <span class="link_name">イベント情報機能</span>
            </a>
            <span class="tooltip">イベント情報機能</span>
        </li>

        <li>
            <a href="{% url 'operator_accounts:account_list' %}">
                <i class="material-symbols-outlined">manage_accounts</i>
                <span class="link_name">アカウント機能</span>
            </a>
            <span class="tooltip">アカウント機能</span>
        </li>

        <li>
            <a href="{% url 'operator_accounts:operator_logout' %}" class="logout">
                <i class="material-symbols-outlined">logout</i>
                <span class="link_name">ログアウト</span>
            </a>
            <span class="tooltip">ログアウト</span>
        </li>
    </ul>
</div>
<!-- ▲ サイドバー（共通） ▲ -->


<!-- ▼ ページごとの中身を入れる部分 ▼ -->
<div class="home_content" id="no name">
    {% block content %}
    {% endblock %}
</div>
<!-- ▲ ページごとの中身 ▲ -->

</body>
</html>

oshiro_navi/oshiro_navi/templates/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}利用者画面{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/user_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/audio_guide.css' %}">
    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
    
    <style>
        .user-icon-img {
            width: 24px;
            height: 24px;
            border-radius: 50%;
            object-fit: cover;
            vertical-align: middle;
            margin-right: 5px;
        }
    </style>
</head>

<body> 
<div class="user-container">
    <div class="logo_content">
        <a href="{% url 'user_accounts:top' %}" class="logo">
            <img src="{% static 'image/top_logo.png' %}" alt="お城ナビロゴ" class="logo_img">
        </a>
    </div>
    <header class="header">



        <!-- スマホ用メニューアイコン -->
        <div class="menu-icon" id="menu-toggle">
            <span class="material-symbols-outlined" id="menu-icon-text">
            menu
            </span>
        </div>
    </header>

            <!-- ナビゲーションバー -->
        <nav class="mobile-nav" id="mobile-nav">
        <ul>
            <li>
            <a style="background-color: white;" href="{% url 'user_accounts:top' %}" class="nav-logo">
                <img src="{% static 'image/top_logo.png' %}" alt="お城ナビロゴ" class="logo_img">
            </a>
            </li>
            <li>
            <a href="{% url 'user_accounts:top' %}">
                <i class="material-symbols-outlined">home</i>
                <span class="link_name">トップ</span>
            </a>
        </li>
            <li>
            <a href="{% url 'usermy_list:oshirolist' %}">
                <i class="material-symbols-outlined">manage_search</i>
                <span class="link_name">お城リスト</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_event_info:event_info' %}">
                <i class="material-symbols-outlined">calendar_month</i>
                <span class="link_name">イベント</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_model_course:modelcoursechoose' %}">
                <i class="material-symbols-outlined">alt_route</i> 
                <span class="link_name">モデルコース</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_audio_guide:qr_scan' %}">
                <i class="material-symbols-outlined">qr_code_2_add</i>
                <span class="link_name">QRコード読み込み</span>
            </a>
        </li>
        <div class="nav-my-page">
            <span class="my-page-text">マイページ</span>
            <li><a href="{% url 'usermy_page:profile' %}">プロフィール</a></li>
            <li><a href="{% url 'usermy_page:oshirostampregistar' %}">お城スタンプ</a></li>
            <li><a href="{% url 'usermy_page:mylistregistar' %}">お城マイリスト</a></li>
            <li><a href="{% url 'user_accounts:logout_check' %}">ログアウト</a></li>
        </div>
        </ul>
        </nav>

        <!-- PC -->
    <ul class="nav">
        <li>
            <a href="{% url 'user_accounts:top' %}">
                <i class="material-symbols-outlined">home</i>
                <span class="link_name">トップ</span>
            </a>
        </li>
        
        <li>
            <a href="{% url 'usermy_list:oshirolist' %}">
                <i class="material-symbols-outlined">manage_search</i>
                <span class="link_name">お城リスト</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_event_info:event_info' %}">
                <i class="material-symbols-outlined">calendar_month</i>
                <span class="link_name">イベント</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_model_course:modelcoursechoose' %}">
                <i class="material-symbols-outlined">alt_route</i> 
                <span class="link_name">モデルコース</span>
            </a>
        </li>
        <li>
            <a href="{% url 'user_audio_guide:qr_scan' %}">
                <i class="material-symbols-outlined">qr_code_2_add</i>
                <span class="link_name">QRコード読み込み</span>
            </a>
        </li>
    </ul>

    <div class="dropdown">
        <a href="#" class="dropdown-btn" id="menuTrigger">
            {% if user.is_authenticated and user.user_profile.profile_image %}
                <img src="{{ user.user_profile.profile_image.url }}" alt="ユーザーアイコン" class="user-icon-img">
            {% else %}
                <i class="material-symbols-outlined">account_circle</i>
            {% endif %}
            <span class="link_name">マイページ</span>
        </a>

        <ul class="dropdown-menu" id="dropdownMenu">
            <li><a href="{% url 'usermy_page:profile' %}">プロフィール</a></li>
            <li><a href="{% url 'usermy_page:oshirostampregistar' %}">お城スタンプ</a></li>
            <li><a href="{% url 'usermy_page:mylistregistar' %}">お城マイリスト</a></li>
            <li><a href="{% url 'user_accounts:logout_check' %}">ログアウト</a></li>
        </ul>
    </div>
</div>

<div class="home_content" id="no name">
    {% block content %}
    {% endblock %}
</div>



<script src="{% static 'JS/user.js' %}"></script>
</body>
<footer class="footer">
    <div class="footer-inner">

        <div class="footer-section">
            <h3 class="wafu-title">あなたと名城を、もっと近くに。</h3>
        </div>
        
    </div>
    <p class="copyright">
        © お城ナビ 日本お城情報サイト
    </p>
    
</footer>
</html>